#!/bin/sh

set -e

printf "\033[0;32mGerando site...\033[0m\n"

hugo -t "m10c"

printf "\033[0;32mEnviando atualizações ao GitHub...\033[0m\n"

git add .

msg="reconstruindo site $(date)"
if [ -n "$*" ]; then
	msg="$*"
fi

git commit -m "$msg" 
git push origin master

printf "\033[0;32mTornado as atualizações públicas...\033[0m\n"

cd public/

printf "\033[0;32mEnviando atualizações ao GitHub...\033[0m\n"

git add .
git commit -m "$msg"
git push origin main

